<template>
    <div class="custom-loading">
        <div class="loadingio-spinner-bean-eater-ev33vk5a1fb">
            <div class="ldio-zqh1ujqci2e">
                <div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
                <div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {};
</script>

<style type="text/css">
.custom-loading {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    background-color: rgba(44, 62, 80, 0.7);
    display: flex;
    justify-content: center;
    align-items: center;
    opacity: 0;
    visibility: hidden;
}
.custom-loading.show {
    opacity: 1;
    visibility: visible;
}
@keyframes ldio-zqh1ujqci2e-1 {
    0% {
        transform: rotate(0deg);
    }
    50% {
        transform: rotate(-45deg);
    }
    100% {
        transform: rotate(0deg);
    }
}
@keyframes ldio-zqh1ujqci2e-2 {
    0% {
        transform: rotate(180deg);
    }
    50% {
        transform: rotate(225deg);
    }
    100% {
        transform: rotate(180deg);
    }
}
.ldio-zqh1ujqci2e > div:nth-child(2) {
    transform: translate(-15px, 0);
}
.ldio-zqh1ujqci2e > div:nth-child(2) div {
    position: absolute;
    top: 23.599999999999998px;
    left: 23.599999999999998px;
    width: 70.8px;
    height: 35.4px;
    border-radius: 70.8px 70.8px 0 0;
    background: #6acbf8;
    animation: ldio-zqh1ujqci2e-1 0.31746031746031744s linear infinite;
    transform-origin: 35.4px 35.4px;
}
.ldio-zqh1ujqci2e > div:nth-child(2) div:nth-child(2) {
    animation: ldio-zqh1ujqci2e-2 0.31746031746031744s linear infinite;
}
.ldio-zqh1ujqci2e > div:nth-child(2) div:nth-child(3) {
    transform: rotate(-90deg);
    animation: none;
}
@keyframes ldio-zqh1ujqci2e-3 {
    0% {
        transform: translate(112.1px, 0);
        opacity: 0;
    }
    20% {
        opacity: 1;
    }
    100% {
        transform: translate(41.3px, 0);
        opacity: 1;
    }
}
.ldio-zqh1ujqci2e > div:nth-child(1) {
    display: block;
}
.ldio-zqh1ujqci2e > div:nth-child(1) div {
    position: absolute;
    top: 54.279999999999994px;
    left: -4.72px;
    width: 9.44px;
    height: 9.44px;
    border-radius: 50%;
    background: #d5df1b;
    animation: ldio-zqh1ujqci2e-3 0.31746031746031744s linear infinite;
}
.ldio-zqh1ujqci2e > div:nth-child(1) div:nth-child(1) {
    animation-delay: -2.1105s;
}
.ldio-zqh1ujqci2e > div:nth-child(1) div:nth-child(2) {
    animation-delay: -1.0395s;
}
.ldio-zqh1ujqci2e > div:nth-child(1) div:nth-child(3) {
    animation-delay: 0s;
}
.loadingio-spinner-bean-eater-ev33vk5a1fb {
    width: 118px;
    height: 118px;
    display: inline-block;
    overflow: hidden;
    background: none;
}
.ldio-zqh1ujqci2e {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
}
.ldio-zqh1ujqci2e div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
